name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:

  build-lod-ubuntu-latest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go 1.18.1
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.1

      - name: Install GEOS
        run: sudo apt update && sudo apt -y install libgeos++-dev libgeos-3.8.0 libgeos-c1v5 libgeos-dev libgeos-doc

      - name: Build
        run: go build -v ./...
