name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:

  test-lod-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Test
      run: go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic
      
    - name: Upload coverage profile to Codecov
      run: bash <(curl -s https://codecov.io/bash)
