name: test

on: ["push", "pull_request"]

jobs:

  test-lod-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Lint code
      run: |
        gofiles=$(find ./ -name '*.go') && [ -z "$gofiles" ] || unformatted=$(goimports -l $gofiles) && [ -z "$unformatted" ] || (echo >&2 "Go files must be formatted with gofmt. Following files has problem: $unformatted" &&  true);
        diff <(echo -n) <(gofmt -s -d .)
        export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
        go get -u golang.org/x/lint/golint
        golint ./...

    - name: Test
      run: go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic

    - name: Coveralls
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_SECRET }}
      run: |
        go get github.com/mattn/goveralls
        go install github.com/mattn/goveralls
        $(go env GOPATH)/bin/goveralls -coverprofile=coverage.txt -service=github
